wallofquotes_app_home:
    path:     /
    defaults: { _controller: WallOfQuotesAppBundle:Default:index }

wallofquotes_quote_index:
    methods: ['GET']
    path: /quotes
    defaults:
        _controller: WallOfQuotesAppBundle:Quote:index

wallofquotes_quote_create:
    methods: ['GET', 'POST']
    path: /quotes/create
    defaults:
        _controller: WallOfQuotesAppBundle:Quote:add

wallofquotes_quote_update:
    methods: ['GET', 'PUT']
    path: /quotes/{id}/edit
    defaults:
        _controller: WallOfQuotesAppBundle:Quote:update
    requirements:
        id: '\d+'

wallofquotes_quote_delete:
    methods: ['DELETE']
    path: /quotes/{id}/delete
    defaults:
        _controller: WallOfQuotesAppBundle:Quote:delete
    requirements:
        id: '\d+'

wallofquotes_author_index:
    methods: ['GET']
    path: /authors
    defaults:
        _controller: WallOfQuotesAppBundle:Author:index

wallofquotes_author_create:
    methods: ['GET', 'POST']
    path: /authors/create
    defaults:
        _controller: WallOfQuotesAppBundle:Author:add

wallofquotes_author_update:
    methods: ['GET', 'PUT']
    path: /authors/{id}/edit
    defaults:
        _controller: WallOfQuotesAppBundle:Author:update
    requirements:
        id: '\d+'

wallofquotes_author_delete:
    methods: ['DELETE']
    path: /authors/{id}/delete
    defaults:
        _controller: WallOfQuotesAppBundle:Author:delete
    requirements:
        id: '\d+'