services:
    wallofquotes.repository.quote:
        class: WallOfQuotes\Bundle\AppBundle\Doctrine\ORM\QuoteRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - WallOfQuotes\Bundle\AppBundle\Entity\Quote
    wallofquotes.repository.author:
        class: WallOfQuotes\Bundle\AppBundle\Doctrine\ORM\AuthorRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - WallOfQuotes\Bundle\AppBundle\Entity\Author
    wallofquotes.form.type.author_choice:
        class: WallOfQuotes\Bundle\AppBundle\Form\Type\AuthorChoiceType
        arguments: ['@wallofquotes.repository.author']
        tags:
            - { name: form.type, alias: wallofquotes_author_choice }
